services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tala-trivia-laravel
    container_name: tala-trivia-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - tala-trivia
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: tala-trivia-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tala-trivia
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: tala-trivia-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tala_trivia
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: tala_trivia
      MYSQL_USER: tala_trivia
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tala-trivia
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    container_name: tala-trivia-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - tala-trivia

networks:
  tala-trivia:
    driver: bridge

volumes:
  dbdata:
    driver: local
